"""expand_comprovante_metadata

Revision ID: 1d6ce1c4554b
Revises: 1e3a810eca22
Create Date: 2026-06-13 11:44:07.377516
"""
from alembic import op
import sqlalchemy as sa



revision = '1d6ce1c4554b'
down_revision = '1e3a810eca22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_sessoes', sa.Column('comprovante_nome_original', sa.String(length=300), nullable=True))
    op.add_column('agenda_sessoes', sa.Column('comprovante_mime', sa.String(length=100), nullable=True))
    op.add_column('agenda_sessoes', sa.Column('comprovante_tamanho', sa.Integer(), nullable=True))
    op.add_column('agenda_sessoes', sa.Column('comprovante_enviado_em', sa.DateTime(), nullable=True))
    op.add_column('despesas', sa.Column('comprovante_nome_original', sa.String(length=300), nullable=True))
    op.add_column('despesas', sa.Column('comprovante_mime', sa.String(length=100), nullable=True))
    op.add_column('despesas', sa.Column('comprovante_tamanho', sa.Integer(), nullable=True))
    op.add_column('despesas', sa.Column('comprovante_enviado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('despesas', 'comprovante_enviado_em')
    op.drop_column('despesas', 'comprovante_tamanho')
    op.drop_column('despesas', 'comprovante_mime')
    op.drop_column('despesas', 'comprovante_nome_original')
    op.drop_column('agenda_sessoes', 'comprovante_enviado_em')
    op.drop_column('agenda_sessoes', 'comprovante_tamanho')
    op.drop_column('agenda_sessoes', 'comprovante_mime')
    op.drop_column('agenda_sessoes', 'comprovante_nome_original')
    # ### end Alembic commands ###
