"""add_comprovante_nome

Revision ID: 1e3a810eca22
Revises: c8473e4a7369
Create Date: 2026-06-13 11:33:26.354255
"""
from alembic import op
import sqlalchemy as sa



revision = '1e3a810eca22'
down_revision = 'c8473e4a7369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_sessoes', sa.Column('comprovante_nome', sa.String(length=200), nullable=True))
    op.add_column('despesas', sa.Column('comprovante_nome', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('despesas', 'comprovante_nome')
    op.drop_column('agenda_sessoes', 'comprovante_nome')
    # ### end Alembic commands ###
