"""add_db_constraints

Revision ID: 29695509e646
Revises: 7365894facdd
Create Date: 2026-06-12 20:26:23.809559
"""
from alembic import op
import sqlalchemy as sa



revision = '29695509e646'
down_revision = '7365894facdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta migração foi mantida intencionalmente vazia para preservar a cadeia linear
    # de revisões do Alembic após consolidação manual do esquema do banco de dados.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
