"""adiciona_campos_sessao_real_e_indices

Revision ID: 449e1cbaefc3
Revises: 29695509e646
Create Date: 2026-06-13 10:32:50.992598
"""
from alembic import op
import sqlalchemy as sa



revision = '449e1cbaefc3'
down_revision = '29695509e646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_sessoes', sa.Column('valor_sessao', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('agenda_sessoes', sa.Column('recorrente', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_constraint(op.f('uq_horario_unico'), 'agenda_sessoes', type_='unique')
    op.create_index(op.f('ix_agenda_sessoes_data_hora_inicio'), 'agenda_sessoes', ['data_hora_inicio'], unique=False)
    op.create_index(op.f('ix_agenda_sessoes_id_paciente'), 'agenda_sessoes', ['id_paciente'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenda_sessoes_id_paciente'), table_name='agenda_sessoes')
    op.drop_index(op.f('ix_agenda_sessoes_data_hora_inicio'), table_name='agenda_sessoes')
    op.create_unique_constraint(op.f('uq_horario_unico'), 'agenda_sessoes', ['data_hora_inicio'], postgresql_nulls_not_distinct=False)
    op.drop_column('agenda_sessoes', 'recorrente')
    op.drop_column('agenda_sessoes', 'valor_sessao')
    # ### end Alembic commands ###
