"""add_login_security_fields

Revision ID: 7365894facdd
Revises: 20260609_0001
Create Date: 2026-06-12 20:16:25.380064
"""
from alembic import op
import sqlalchemy as sa



revision = '7365894facdd'
down_revision = '20260609_0001'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('usuarios', sa.Column('tentativas_login', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('usuarios', sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('trocar_senha_proximo_login', sa.Boolean(), nullable=False, server_default='false'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'trocar_senha_proximo_login')
    op.drop_column('usuarios', 'bloqueado_ate')
    op.drop_column('usuarios', 'tentativas_login')
    # ### end Alembic commands ###
