"""remove_excecoes_e_adiciona_constraints

Revision ID: 9067eb09bf41
Revises: 449e1cbaefc3
Create Date: 2026-06-13 11:02:47.157995
"""
from alembic import op
import sqlalchemy as sa



revision = '9067eb09bf41'
down_revision = '449e1cbaefc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    from sqlalchemy import text, inspect
    
    # 1. Checagem prévia de duplicatas em agenda_sessoes
    dup_query = text(
        "SELECT id_paciente, data_hora_inicio, COUNT(*) "
        "FROM agenda_sessoes "
        "GROUP BY id_paciente, data_hora_inicio "
        "HAVING COUNT(*) > 1"
    )
    duplicatas = connection.execute(dup_query).fetchall()
    if duplicatas:
        import sys
        sys.stderr.write("\n" + "="*80 + "\n")
        sys.stderr.write("ERRO CRÍTICO DE MIGRAÇÃO: Foram encontradas duplicatas em agenda_sessoes!\n")
        for row in duplicatas:
            sys.stderr.write(f"Paciente: {row[0]} | Horário: {row[1]} | Ocorrências: {row[2]}\n")
        sys.stderr.write("A migração uq_paciente_horario falharia. Resolva as duplicatas no banco antes de prosseguir.\n")
        sys.stderr.write("="*80 + "\n\n")
        raise Exception("Duplicatas detectadas em agenda_sessoes. Migração abortada.")

    # 2. Adição de colunas e criação de índices/constraints
    op.add_column('agenda_sessoes', sa.Column('data_pagamento', sa.Date(), nullable=True))
    op.create_index(op.f('ix_agenda_sessoes_status_pagamento'), 'agenda_sessoes', ['status_pagamento'], unique=False)
    op.create_index(op.f('ix_agenda_sessoes_status_presenca'), 'agenda_sessoes', ['status_presenca'], unique=False)
    op.create_unique_constraint('uq_paciente_horario', 'agenda_sessoes', ['id_paciente', 'data_hora_inicio'])
    op.create_check_constraint('ck_valor_sessao_sess_pos', 'agenda_sessoes', 'valor_sessao >= 0')
    op.create_check_constraint('ck_valor_sessao_hist_pos', 'contratos_historico', 'valor_sessao >= 0')

    # 3. Migração de dados de excecoes_horario para agenda_sessoes
    inspector = inspect(connection)
    if "excecoes_horario" in inspector.get_table_names():
        from sqlalchemy import MetaData, Table, select
        from sqlalchemy.dialects.postgresql import insert as pg_insert
        meta = MetaData()
        excecoes = Table('excecoes_horario', meta, autoload_with=connection)
        agenda = Table('agenda_sessoes', meta, autoload_with=connection)
        
        rows = connection.execute(select(excecoes)).fetchall()
        if rows:
            print(f"INFO [alembic] Encontradas {len(rows)} excecoes de horario. Migrando...")
            for r in rows:
                id_paciente = r.id_paciente
                tipo = r.tipo
                data_especifica = r.data_especifica
                horario_alvo = r.horario_alvo
                
                if tipo == 'pontual' and data_especifica and horario_alvo:
                    try:
                        ini_str, fim_str = horario_alvo.split(" - ")
                        hi, mi = map(int, ini_str.split(":"))
                        hf, mf = map(int, fim_str.split(":"))
                        from datetime import datetime, time
                        dt_inicio = datetime.combine(data_especifica, time(hi, mi))
                        dt_fim = datetime.combine(data_especifica, time(hf, mf))
                        
                        stmt = pg_insert(agenda).values(
                            id_paciente=id_paciente,
                            data_hora_inicio=dt_inicio,
                            data_hora_fim=dt_fim,
                            status_presenca=sa.cast('AGENDADA', sa.Enum(name='status_presenca')),
                            status_pagamento=sa.cast('PENDENTE', sa.Enum(name='status_pagamento')),
                            confirmacao_enviada=False,
                            recorrente=False
                        ).on_conflict_do_nothing(
                            index_elements=['id_paciente', 'data_hora_inicio']
                        )
                        connection.execute(stmt)
                    except Exception as err:
                        print(f"WARNING [alembic] Erro ao migrar excecao ID {r.id_excecao}: {err}")
                elif tipo == 'recorrente':
                    print(f"WARNING [alembic] Exceção recorrente encontrada para id_paciente={r.id_paciente}: "
                          f"semana={r.semana_do_mes}, dia={r.dia_alvo}, horario={r.horario_alvo}. "
                          f"Por favor, configure o novo contrato do paciente para refletir esta recorrência.")

    # 4. Remoção da tabela obsoleta
    op.drop_table('excecoes_horario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_valor_sessao_hist_pos', 'contratos_historico', type_='check')
    op.drop_constraint('ck_valor_sessao_sess_pos', 'agenda_sessoes', type_='check')
    op.drop_constraint('uq_paciente_horario', 'agenda_sessoes', type_='unique')
    op.drop_index(op.f('ix_agenda_sessoes_status_presenca'), table_name='agenda_sessoes')
    op.drop_index(op.f('ix_agenda_sessoes_status_pagamento'), table_name='agenda_sessoes')
    op.drop_column('agenda_sessoes', 'data_pagamento')
    op.create_table('excecoes_horario',
    sa.Column('id_excecao', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('semana_do_mes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_especifica', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dia_alvo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('horario_alvo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name=op.f('excecoes_horario_id_paciente_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_excecao', name=op.f('excecoes_horario_pkey'))
    )
    # ### end Alembic commands ###
