"""remove_excecoes_e_adiciona_constraints

Revision ID: 9067eb09bf41
Revises: 449e1cbaefc3
Create Date: 2026-06-13 11:02:47.157995
"""
from alembic import op
import sqlalchemy as sa



revision = '9067eb09bf41'
down_revision = '449e1cbaefc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excecoes_horario')
    op.add_column('agenda_sessoes', sa.Column('data_pagamento', sa.Date(), nullable=True))
    op.create_index(op.f('ix_agenda_sessoes_status_pagamento'), 'agenda_sessoes', ['status_pagamento'], unique=False)
    op.create_index(op.f('ix_agenda_sessoes_status_presenca'), 'agenda_sessoes', ['status_presenca'], unique=False)
    op.create_unique_constraint('uq_paciente_horario', 'agenda_sessoes', ['id_paciente', 'data_hora_inicio'])
    op.create_check_constraint('ck_valor_sessao_sess_pos', 'agenda_sessoes', 'valor_sessao >= 0')
    op.create_check_constraint('ck_valor_sessao_hist_pos', 'contratos_historico', 'valor_sessao >= 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_valor_sessao_hist_pos', 'contratos_historico', type_='check')
    op.drop_constraint('ck_valor_sessao_sess_pos', 'agenda_sessoes', type_='check')
    op.drop_constraint('uq_paciente_horario', 'agenda_sessoes', type_='unique')
    op.drop_index(op.f('ix_agenda_sessoes_status_presenca'), table_name='agenda_sessoes')
    op.drop_index(op.f('ix_agenda_sessoes_status_pagamento'), table_name='agenda_sessoes')
    op.drop_column('agenda_sessoes', 'data_pagamento')
    op.create_table('excecoes_horario',
    sa.Column('id_excecao', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('semana_do_mes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_especifica', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dia_alvo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('horario_alvo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name=op.f('excecoes_horario_id_paciente_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_excecao', name=op.f('excecoes_horario_pkey'))
    )
    # ### end Alembic commands ###
