"""add_db_constraints_for_financial_coherence

Revision ID: a8de83320acd
Revises: 5d58247016ff
Create Date: 2026-06-14 17:06:05.682868
"""
from alembic import op
import sqlalchemy as sa



revision = 'a8de83320acd'
down_revision = '5d58247016ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agenda_sessoes', 'valor_sessao',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    
    op.create_check_constraint(
        'ck_sessao_pago_tem_data',
        'agenda_sessoes',
        "CAST(status_pagamento AS VARCHAR) != 'PAGO' OR data_pagamento IS NOT NULL"
    )
    
    op.create_check_constraint(
        'ck_despesa_paga_tem_data',
        'despesas',
        "NOT paga OR data_pagamento IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_despesa_paga_tem_data', 'despesas', type_='check')
    op.drop_constraint('ck_sessao_pago_tem_data', 'agenda_sessoes', type_='check')
    op.alter_column('agenda_sessoes', 'valor_sessao',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
