"""add_sistema_status_e_fechamentos

Revision ID: c8473e4a7369
Revises: 9067eb09bf41
Create Date: 2026-06-13 11:20:22.606387
"""
from alembic import op
import sqlalchemy as sa



revision = 'c8473e4a7369'
down_revision = '9067eb09bf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamentos_mensais',
    sa.Column('id_fechamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fechado_por', sa.String(length=50), nullable=False),
    sa.Column('total_recebido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_despesas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_fechamento'),
    sa.UniqueConstraint('mes_referencia')
    )
    op.create_table('sistema_status',
    sa.Column('id_status', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('quando', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sistema_status')
    op.drop_table('fechamentos_mensais')
    # ### end Alembic commands ###
